image: limaofeng/alpine-gradle

before_script:
  - cp -rf .gradle ~/.gradle
  - echo 10.45.21.126 maven.zbsg.com.cn >> /etc/hosts

stages:
  - build
  - test
  - sonar
  - deploy

build:
  script:
    - gradle clean classes -x test
  tags:
    - docker

sonar:
  script:
      - gradle sonar -x test
  tags:
    - docker
  only:
    - tags