image: java:openjdk-8-jdk

before_script:
  - curl -s https://get.sdkman.io | bash
  - sdk install gradle 3.0
  - chmod u+x ./gradlew

build:
  script:
    - gradle wrapper
    - ./gradlew sonar -x test
  artifacts:
    paths:
    - build/libs/
  tags:
    - docker