image: index.docker.io/niaquinto/gradle

before_script:
  - chmod u+x ./gradlew

build:
  script:
    - gradle wrapper
    - ./gradlew sonar -x test
  artifacts:
    paths:
    - build/libs/
  tags:
    - docker