image: limaofeng/alpine-gradle

before_script:
  - export LANG="zh_CN.UTF-8"
  - cp -rf .gradle ~/.gradle
  - echo 10.45.21.126 maven.zbsg.com.cn >> /etc/hosts

stages:
  - build
  - test
  - sonar
  - deploy

build:
  script:
    - gradle clean classes -x test
  tags:
    - docker

#sonar:
#  script:
#      - gradle sonar -x test
#  tags:
#    - docker
#  only:
#    - tags

deploy:
  script:
      - gradle upload -x test
  tags:
    - docker
  only:
    - tags